name: Auto Green Commit

on:
  schedule:
    - cron: "22 17 * * *"  # Jalankan setiap hari pukul 00:00 UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "thrain-code"
          git config --global user.email "arkadanisaysstuff@gmail.com"

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Auto commit at $(date)" >> log.txt
          git add log.txt
          git commit -m "Automated commit on $(date)" || exit 0
          git push origin main
