name: Auto Green Commit

on:
  schedule:
    - cron: "42 17 * * *" 
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "thrain-code"
          git config --global user.email "arkadanisaysstuff@gmail.com"

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "thrain-code"
          git config --global user.email "arkadanisaysstuff@gmail.com"
          git add log.txt
          git commit -m "Automated commit on $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push https://thrain-code:${{ secrets.GH_TOKEN }}@github.com/thrain-code/commit.git